services:
  vxtwitter-bot:
    build: .
    container_name: vxtwitter-discord-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    env_file:
      - .env
    volumes:
      - ./logs:/root/logs
